-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- List current monitors and supported resolutions with: hyprctl monitors all

local omarchy_gdk_scale = 2
local omarchy_monitor_scale = 1.6

hl.env("GDK_SCALE", tostring(omarchy_gdk_scale))
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = omarchy_monitor_scale })

-- Configure a specific monitor.
-- hl.monitor({ output = "DP-2", mode = "2560x1440@144", position = "0x0", scale = 1 })

-- Portrait/rotated secondary monitor (transform: 1 = 90°, 3 = 270°).
-- hl.monitor({ output = "DP-2", mode = "preferred", position = "auto", scale = 1, transform = 1 })

-- >>> omarchy-monitor-arranger >>>
-- Generated by omarchy-monitor-arranger on 2026-10-02 12:06.
-- Every display is pinned: leaving one on "auto" makes Hyprland
-- reflow it around the pinned ones and undo this arrangement.
-- Edits here are replaced the next time you save from the widget;
-- anything outside these markers is left alone.
-- Layout: 3750x900 logical px across 2 display(s).

-- DELL S2721DGF (DP-1) 1600x900 logical at 2150,0
hl.monitor({ output = "desc:Dell Inc. DELL S2721DGF", mode = "2560x1440@165", position = "2150x0", scale = 1.6 })

-- DELL S3422DWG (DP-2) 2150x900 logical at 0,0
hl.monitor({ output = "desc:Dell Inc. DELL S3422DWG", mode = "3440x1440@144", position = "0x0", scale = 1.6 })
-- <<< omarchy-monitor-arranger <<<
